((library:r6rs-core
   &condition
   &error
   &message
   &non-continuable
   &serious
   &violation
   &warning
   |'|
   *
   +
   |,|
   |,@|
   -
   ->exact
   ->inexact
   /
   |;|
   <
   <=
   =
   =>
   >
   >=
   |`|
   abs
   acos
   and
   and
   angle
   append
   apply
   asin
   assoc
   assq
   assv
   atan
   begin
   boolean?
   caar
   cadr
   call-with-current-continuation
   call-with-values
   call/cc
   car
   case
   cdddar
   cddddr
   cdr
   ceiling
   char->integer
   char-alphabetic?
   char-ci<=?
   char-ci<?
   char-ci=?
   char-ci>=?
   char-ci>?
   char-downcase
   char-lower-case?
   char-numeric?
   char-ready?
   char-upcase
   char-upper-case?
   char-whitespace?
   char<=?
   char<?
   char=?
   char>=?
   char>?
   char?
   complex?
   cond
   condition
   condition-has-type?
   condition-ref
   condition-type?
   condition?
   cons
   cos
   define
   define-condition-type
   define-syntax
   denominator
   do
   dynamic-wind
   else
   eq?
   equal?
   eqv?
   even?
   exact?
   exp
   expt
   extract-condition
   floor
   for-each
   gcd
   guard
   if
   imag-part
   inexact?
   integer->char
   integer?
   lambda
   lcm
   length
   let
   let*
   let-syntax
   let-values
   letrec
   letrec*
   letrec-syntax
   letrec-values
   list
   list->string
   list->vector
   list-ref
   list-tail
   list?
   log
   magnitude
   make-compound-condition
   make-condition
   make-condition-type
   make-polar
   make-rectangular
   make-string
   make-vector
   map
   max
   member
   memq
   memv
   min
   negative?
   not
   null?
   number->string
   number?
   numerator
   odd?
   or
   or
   pair?
   positive?
   procedure?
   quasiquote
   quote
   raise
   raise-continuable
   rational?
   rationalize
   real-part
   real?
   reverse
   round
   set!
   set-car!
   set-cdr!
   sin
   sqrt
   string
   string->list
   string->number
   string->symbol
   string-append
   string-ci<=?
   string-ci<?
   string-ci=?
   string-ci>=?
   string-ci>?
   string-copy
   string-fill!
   string-length
   string-ref
   string-set!
   string<=?
   string<?
   string=?
   string>=?
   string>?
   string?
   substring
   symbol->string
   symbol?
   tan
   truncate
   unquote
   unquote-splicing
   values
   vector
   vector->list
   vector-fill!
   vector-length
   vector-ref
   vector-set!
   vector?
   with-exception-handler
   zero?)
 (library:syntax-rules ... syntax-rules)
 (library:syntax-case
   bound-identifier=?
   datum->syntax
   free-identifier=?
   generate-temporaries
   identifier-syntax
   identifier?
   make-variable-transformer
   syntax
   syntax->datum
   syntax-case
   with-syntax)
 (library:bytes
   bytes->sint-list
   bytes->u8-list
   bytes->uint-list
   bytes-copy
   bytes-copy!
   bytes-length
   bytes-s16-native-ref
   bytes-s16-native-set!
   bytes-s16-ref
   bytes-s16-set!
   bytes-s32-native-ref
   bytes-s32-native-set!
   bytes-s32-ref
   bytes-s32-set!
   bytes-s64-native-ref
   bytes-s64-native-set!
   bytes-s64-ref
   bytes-s64-set!
   bytes-s8-ref
   bytes-s8-set!
   bytes-sint-ref
   bytes-sint-set!
   bytes-u16-native-ref
   bytes-u16-native-set!
   bytes-u16-ref
   bytes-u16-set!
   bytes-u32-native-ref
   bytes-u32-native-set!
   bytes-u32-ref
   bytes-u32-set!
   bytes-u64-native-ref
   bytes-u64-native-set!
   bytes-u64-ref
   bytes-u64-set!
   bytes-u8-ref
   bytes-u8-set!
   bytes-uint-ref
   bytes-uint-set!
   bytes=?
   bytes?
   endianness
   make-bytes
   native-endianness
   sint-list->bytes
   u8-list->bytes
   uint-list->bytes)
 (library:arithmetic-generic
   *
   +
   -
   -
   /
   /
   <
   <=
   =
   >
   >=
   abs
   acos
   angle
   asin
   atan
   atan
   ceiling
   complex?
   cos
   denominator
   div
   div+mod
   div0
   div0+mod0
   even?
   exact->inexact
   exact?
   exp
   expt
   finite?
   floor
   gcd
   imag-part
   inexact->exact
   inexact?
   infinite?
   integer-valued?
   integer?
   lcm
   log
   magnitude
   make-polar
   make-rectangular
   max
   min
   mod
   mod0
   nan?
   negative?
   number->string
   number->string
   number->string
   number?
   numerator
   odd?
   positive?
   rational-valued?
   rational?
   rationalize
   real->flonum
   real-part
   real-valued?
   real?
   round
   sin
   sqrt
   string->number
   string->number
   tan
   truncate
   zero?)
 (library:arithmetic-fixnum
   fixnum*
   fixnum*/carry
   fixnum+
   fixnum+/carry
   fixnum-
   fixnum-
   fixnum-/carry
   fixnum-and
   fixnum-arithmetic-shift
   fixnum-arithmetic-shift-left
   fixnum-arithmetic-shift-right
   fixnum-bit-count
   fixnum-bit-field
   fixnum-bit-set?
   fixnum-copy-bit
   fixnum-copy-bit-field
   fixnum-div
   fixnum-div+mod
   fixnum-div0
   fixnum-div0+mod0
   fixnum-even?
   fixnum-first-bit-set
   fixnum-if
   fixnum-ior
   fixnum-length
   fixnum-logical-shift-left
   fixnum-logical-shift-right
   fixnum-max
   fixnum-min
   fixnum-mod
   fixnum-mod0
   fixnum-negative?
   fixnum-not
   fixnum-odd?
   fixnum-positive?
   fixnum-reverse-bit-field
   fixnum-rotate-bit-field
   fixnum-width
   fixnum-xor
   fixnum-zero?
   fixnum<
   fixnum<=
   fixnum=
   fixnum>
   fixnum>=
   fixnum?
   greatest-fixnum
   least-fixnum)
 (library:arithmetic-flonum
   fixnum->flonum
   fl*
   fl+
   fl-
   fl-
   fl/
   fl/
   fl<
   fl<=
   fl=
   fl>
   fl>=
   flabs
   flasin
   flatan
   flceiling
   flcos
   fldenominator
   fldiv
   fldiv+mod
   fldiv0
   fldiv0+mod0
   fleven?
   flexp
   flexpt
   flfinite?
   flfloor
   flinfinite?
   flinteger?
   fllog
   flmax
   flmin
   flmod
   flmod0
   flnan?
   flnegative?
   flnumerator
   flodd?
   flonum?
   flpositive?
   flround
   flsin
   flsqrt
   fltan
   fltruncate
   flzero?)
 (library:arithmetic-fx
   fx*
   fx+
   fx-
   fx-
   fx<
   fx<=
   fx=
   fx>
   fx>=
   fxand
   fxarithmetic-shift
   fxarithmetic-shift-left
   fxarithmetic-shift-right
   fxbit-count
   fxbit-field
   fxbit-set?
   fxcopy-bit
   fxcopy-bit-field
   fxdiv
   fxdiv+mod
   fxdiv0
   fxdiv0+mod0
   fxeven?
   fxfirst-bit-set
   fxif
   fxior
   fxlength
   fxmax
   fxmin
   fxmod
   fxmod0
   fxnegative?
   fxnot
   fxodd?
   fxpositive?
   fxreverse-bit-field
   fxrotate-bit-field
   fxxor
   fxzero?)
 (library:arithmetic-exact
   exact*
   exact+
   exact-
   exact-
   exact-abs
   exact-and
   exact-arithmetic-shift
   exact-arithmetic-shift-left
   exact-arithmetic-shift-right
   exact-bit-count
   exact-bit-field
   exact-bit-set?
   exact-ceiling
   exact-complex?
   exact-copy-bit
   exact-copy-bit-field
   exact-denominator
   exact-div
   exact-div+mod
   exact-div0
   exact-div0+mod0
   exact-even?
   exact-expt
   exact-first-bit-set
   exact-floor
   exact-gcd
   exact-if
   exact-imag-part
   exact-integer-sqrt
   exact-integer?
   exact-ior
   exact-lcm
   exact-length
   exact-make-rectangular
   exact-max
   exact-min
   exact-mod
   exact-mod0
   exact-negative?
   exact-not
   exact-number?
   exact-numerator
   exact-odd?
   exact-positive?
   exact-rational?
   exact-real-part
   exact-reverse-bit-field
   exact-rotate-bit-field
   exact-round
   exact-truncate
   exact-xor
   exact-zero?
   exact/
   exact/
   exact<=?
   exact<?
   exact=
   exact>=?
   exact>?)
 (library:arithmetic-inexact
   inexact*
   inexact+
   inexact-
   inexact-
   inexact-abs
   inexact-angle
   inexact-asin
   inexact-atan
   inexact-atan
   inexact-ceiling
   inexact-complex?
   inexact-cos
   inexact-denominator
   inexact-div
   inexact-div+mod
   inexact-div0
   inexact-div0+mod0
   inexact-even?
   inexact-exp
   inexact-expt
   inexact-finite?
   inexact-floor
   inexact-gcd
   inexact-imag-part
   inexact-infinite?
   inexact-integer?
   inexact-lcm
   inexact-log
   inexact-magnitude
   inexact-make-polar
   inexact-make-rectangular
   inexact-max
   inexact-min
   inexact-mod
   inexact-mod0
   inexact-nan?
   inexact-negative?
   inexact-number?
   inexact-numerator
   inexact-odd?
   inexact-positive?
   inexact-rational?
   inexact-real-part
   inexact-real?
   inexact-round
   inexact-sin
   inexact-sqrt
   inexact-tan
   inexact-truncate
   inexact-zero?
   inexact/
   inexact/
   inexact<=?
   inexact<?
   inexact=?
   inexact>=?
   inexact>?)
 (library:records-procedural
   make-record-constructor-descriptor
   make-record-type-descriptor
   record-accessor
   record-constructor
   record-mutator
   record-predicate
   record-type-descriptor?)
 (library:records-explicit
   define-record-type
   record-constructor-descriptor
   record-type-descriptor)
 (library:records-implicit
   define-record-type
   record-constructor-descriptor
   record-type-descriptor)
 (library:records-reflection
   record-field-mutable?
   record-rtd
   record-type-field-names
   record-type-generative?
   record-type-name
   record-type-opaque?
   record-type-parent
   record-type-sealed?
   record-type-uid
   record?)
 (library:promises delay force)
 (library:eval eval eval-library library-environment load)
 (library:r5rs-compatibility
   exact->inexact
   inexact->exact
   modulo
   null-environment
   quotient
   remainder
   scheme-report-environment)
 (library:obsolete interaction-environment transcript-off transcript-on))
