#!/bin/sh
scheme48 <<EOF
,batch on
,config ,load /afs/wsi/home/sperber/soft/SSAX/lib/packages.scm
,open sxml-to-html sxml-tree-trans
;; ,load /afs/wsi/home/sperber/public_html/template.scm
,load $*
EOF
